# Copyright (c) 2010 ThoughtWorks Inc. (http://thoughtworks.com)
# Licenced under the MIT License (http://www.opensource.org/licenses/mit-license.php)

# This file was generated by the "jdbc" generator, which is provided
# by the activerecord-jdbc-adapter gem.
#
# This file allows you to use Rails' various db:* tasks with JDBC.
if defined?(JRUBY_VERSION)
  require 'jdbc_adapter'
  require 'jdbc_adapter/rake_tasks'
end
